# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRN2okW19lXnOPbpSGcnf0CfcfAQjxSV
"""

!pip install pandas requests lxml

import pandas as pd
import time

def scrape_stat_category(stat_id):

    base_url = f"https://www.ncaa.com/stats/lacrosse-women/d1/current/team/{stat_id}"

    all_pages = []
    page = 1

    while True:

        if page == 1:
            url = base_url
        else:
            url = f"{base_url}/p{page}"

        print(f"Scraping: {url}")

        try:
            tables = pd.read_html(url)

            # NCAA tables are usually first table
            df = tables[0]

            # Stop if page is empty
            if df.shape[0] == 0:
                break

            all_pages.append(df)
            page += 1

            time.sleep(2)  # be polite

        except:
            print("No more pages.")
            break

    full_df = pd.concat(all_pages, ignore_index=True)

    return full_df

assists_df = scrape_stat_category(480)
assists_df.head(100)

# Make sure column name matches exactly
assists_df.columns = assists_df.columns.str.lower().str.replace(" ", "_")

# Convert rank to numeric (blanks become NaN)
assists_df["rank"] = pd.to_numeric(assists_df["rank"], errors="coerce")

# Forward fill missing ranks
assists_df["rank"] = assists_df["rank"].ffill()

assists_df = assists_df.sort_values("rank")

assists_df["rank"] = assists_df["rank"].astype(int)

assists_df.head(10)

assists_df.to_csv("assists.csv", index=False)

from google.colab import files
files.download("assists.csv")

stat_categories = {
    "assists": 480,
    "draw_controls": 262,
    "free_position": 1082,
    "shots_on_goal": 1162,
    "shots_per_game": 1160,
    "goals": 246,
    "caused_turnovers": 264

}

all_stats = {}

for stat_name, stat_id in stat_categories.items():
    print(f"\nScraping {stat_name}")
    df = scrape_stat_category(stat_id)

    df.columns = df.columns.str.lower().str.replace(" ", "_")
    df = df[df["team"] != "Team"]
    df = df.dropna(subset=["team"])

    all_stats[stat_name] = df

for name, df in all_stats.items():
    print("\n", name.upper())
    print(df.columns)
    print(df.head(2))

cleaned_stats = {}

for stat_name, df in all_stats.items():

    df.columns = df.columns.str.lower().str.replace(" ", "_")
    df = df[df["team"] != "Team"]
    df = df.dropna(subset=["team"])

    # Drop rank column if it exists
    df = df.drop(columns=["rank"], errors="ignore")

    # Identify stat column (usually last column)
    stat_column = df.columns[-1]

    # Keep only team + stat
    df = df[["team", stat_column]]

    # Rename stat column to stat_name
    df = df.rename(columns={stat_column: stat_name})

    cleaned_stats[stat_name] = df

master_df = list(cleaned_stats.values())[0]

for stat_name, df in list(cleaned_stats.items())[1:]:
  master_df = master_df.merge(df, on="team", how="outer")

master_df.head()

for col in master_df.columns:
  if col != "team":
    master_df[col] = pd.to_numeric(master_df[col], errors="coerce")

for name, df in all_stats.items():
    print("\n", name.upper())
    print(df.columns)

cleaned_stats = {}

games_df = None  # we’ll store GP here

for stat_name, df in all_stats.items():

    df.columns = df.columns.str.lower().str.replace(" ", "_")
    df = df[df["team"] != "Team"]
    df = df.dropna(subset=["team"])

    # Save GP only once
    if "games" in df.columns and games_df is None:
        games_df = df[["team", "games"]].copy()
        games_df = games_df.rename(columns={"games": "games_played"})

    # Drop rank and gp from stat tables
    df = df.drop(columns=["rank", "games"], errors="ignore")

    # Identify stat column (usually last column)
    stat_column = df.columns[-1]

    df = df[["team", stat_column]]
    df = df.rename(columns={stat_column: stat_name})

    cleaned_stats[stat_name] = df

master_df = None

for stat_name, df in cleaned_stats.items():

    if master_df is None:
        master_df = df
    else:
        master_df = master_df.merge(df, on="team", how="outer")



master_df = games_df

for stat_name, df in cleaned_stats.items():
  master_df = master_df.merge(df, on="team", how="outer")

print(master_df.shape)
master_df.head()

master_df.duplicated(subset="team").sum()

master_df.isna().sum()

master_df.columns = (
    master_df.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_per_")
)

master_df.to_csv("ncaa_womens_lacrosse_team_stats_2026.csv", index=False)

from google.colab import files
files.download("ncaa_womens_lacrosse_team_stats_2026.csv")

